-- Flywheel refill: real Google-popularity queries (autocomplete harvest, 2026-06-26),
-- deduped against the existing 182 seeded keywords by category signature.
-- Priority scaled by harvested popularity count (n): higher n -> higher priority.
INSERT OR IGNORE INTO keyword_queue (keyword, priority, status, created_at) VALUES
('best drill for home use', 60, 'pending', strftime('%s','now')),
('best vacuum for pet hair', 55, 'pending', strftime('%s','now')),
('best power supply for pc', 55, 'pending', strftime('%s','now')),
('best hiking boots for men', 55, 'pending', strftime('%s','now')),
('best phone case for iphone 17', 55, 'pending', strftime('%s','now')),
('best monitor arm for ultrawide', 55, 'pending', strftime('%s','now')),
('best electric shaver for women', 55, 'pending', strftime('%s','now')),
('best cpu 2026', 50, 'pending', strftime('%s','now')),
('best router 2026', 50, 'pending', strftime('%s','now')),
('best sheets 2026', 50, 'pending', strftime('%s','now')),
('best air purifier', 50, 'pending', strftime('%s','now')),
('best luggage 2026', 50, 'pending', strftime('%s','now')),
('best running shoes', 50, 'pending', strftime('%s','now')),
('best microwave 2026', 50, 'pending', strftime('%s','now')),
('best smart lock 2026', 50, 'pending', strftime('%s','now')),
('best hair dryer 2026', 50, 'pending', strftime('%s','now')),
('best vr headset 2026', 50, 'pending', strftime('%s','now')),
('best lawn mower 2026', 50, 'pending', strftime('%s','now')),
('best dishwashers 2026', 50, 'pending', strftime('%s','now')),
('best mouse for gaming', 50, 'pending', strftime('%s','now')),
('best massage gun 2026', 50, 'pending', strftime('%s','now')),
('best pc case under 100', 50, 'pending', strftime('%s','now')),
('best refrigerator 2026', 50, 'pending', strftime('%s','now')),
('best gaming chair 2026', 50, 'pending', strftime('%s','now')),
('best controller for pc', 50, 'pending', strftime('%s','now')),
('best graphics card 2026', 50, 'pending', strftime('%s','now')),
('best power station 2026', 50, 'pending', strftime('%s','now')),
('best video doorbell 2026', 50, 'pending', strftime('%s','now')),
('best paper shredder 2026', 50, 'pending', strftime('%s','now')),
('best pillow for neck pain', 50, 'pending', strftime('%s','now')),
('best water bottle for gym', 50, 'pending', strftime('%s','now')),
('best smart thermostat 2026', 50, 'pending', strftime('%s','now')),
('best mattress for back pain', 50, 'pending', strftime('%s','now')),
('best bluetooth speaker 2026', 50, 'pending', strftime('%s','now')),
('best pressure washer for cars', 50, 'pending', strftime('%s','now')),
('best security camera for home', 50, 'pending', strftime('%s','now')),
('best external hard drive for pc', 50, 'pending', strftime('%s','now')),
('best ai', 45, 'pending', strftime('%s','now')),
('best cab', 45, 'pending', strftime('%s','now')),
('best egg', 45, 'pending', strftime('%s','now')),
('best tvs', 45, 'pending', strftime('%s','now')),
('best hysa', 45, 'pending', strftime('%s','now')),
('best xbox', 45, 'pending', strftime('%s','now')),
('best asian', 45, 'pending', strftime('%s','now')),
('best jokes', 45, 'pending', strftime('%s','now')),
('best vodka', 45, 'pending', strftime('%s','now')),
('best animes', 45, 'pending', strftime('%s','now')),
('best juicer', 45, 'pending', strftime('%s','now')),
('best kc bbq', 45, 'pending', strftime('%s','now')),
('best kindle', 45, 'pending', strftime('%s','now')),
('best quotes', 45, 'pending', strftime('%s','now')),
('best yogurt', 45, 'pending', strftime('%s','now')),
('best phones', 45, 'pending', strftime('%s','now')),
('best grills', 45, 'pending', strftime('%s','now')),
('best jeanist', 45, 'pending', strftime('%s','now')),
('best western', 45, 'pending', strftime('%s','now')),
('best cd rates', 45, 'pending', strftime('%s','now')),
('best dog food', 45, 'pending', strftime('%s','now')),
('best egg loan', 45, 'pending', strftime('%s','now')),
('best medicine', 45, 'pending', strftime('%s','now')),
('best one tire', 45, 'pending', strftime('%s','now')),
('best yoga mat', 45, 'pending', strftime('%s','now')),
('best bbq 2026', 45, 'pending', strftime('%s','now')),
('best dad jokes', 45, 'pending', strftime('%s','now')),
('best keyboards', 45, 'pending', strftime('%s','now')),
('best knife set', 45, 'pending', strftime('%s','now')),
('best olive oil', 45, 'pending', strftime('%s','now')),
('best sunscreen', 45, 'pending', strftime('%s','now')),
('best tv brands', 45, 'pending', strftime('%s','now')),
('best asian menu', 45, 'pending', strftime('%s','now')),
('best hybrid suv', 45, 'pending', strftime('%s','now')),
('best toothpaste', 45, 'pending', strftime('%s','now')),
('best zyn flavor', 45, 'pending', strftime('%s','now')),
('best mouse trap', 45, 'pending', strftime('%s','now')),
('best mouse pads', 45, 'pending', strftime('%s','now')),
('best mouse bait', 45, 'pending', strftime('%s','now')),
('best ssd brands', 45, 'pending', strftime('%s','now')),
('best ssd drives', 45, 'pending', strftime('%s','now')),
('best cpu cooler', 45, 'pending', strftime('%s','now')),
('best tv antenna', 45, 'pending', strftime('%s','now')),
('best vacuum mop', 45, 'pending', strftime('%s','now')),
('best drill bits', 45, 'pending', strftime('%s','now')),
('best mixer 2026', 45, 'pending', strftime('%s','now')),
('best dry shampoo', 45, 'pending', strftime('%s','now')),
('best of the best', 45, 'pending', strftime('%s','now')),
('best self tanner', 45, 'pending', strftime('%s','now')),
('best weed killer', 45, 'pending', strftime('%s','now')),
('best router bits', 45, 'pending', strftime('%s','now')),
('best nasal spray', 45, 'pending', strftime('%s','now')),
('best phone plans', 45, 'pending', strftime('%s','now')),
('best dash camera', 45, 'pending', strftime('%s','now')),
('best drill brand', 45, 'pending', strftime('%s','now')),
('best grill brush', 45, 'pending', strftime('%s','now')),
('best credit cards', 45, 'pending', strftime('%s','now')),
('best western plus', 45, 'pending', strftime('%s','now')),
('best xbox console', 45, 'pending', strftime('%s','now')),
('best xbox headset', 45, 'pending', strftime('%s','now')),
('best mouse killer', 45, 'pending', strftime('%s','now')),
('best router table', 45, 'pending', strftime('%s','now')),
('best phone camera', 45, 'pending', strftime('%s','now')),
('best luggage sets', 45, 'pending', strftime('%s','now')),
('best luggage tags', 45, 'pending', strftime('%s','now')),
('best grill brands', 45, 'pending', strftime('%s','now')),
('best nas hdd 2026', 45, 'pending', strftime('%s','now')),
('best gamepad 2026', 45, 'pending', strftime('%s','now')),
('best documentaries', 45, 'pending', strftime('%s','now')),
('best electric cars', 45, 'pending', strftime('%s','now')),
('best food derby ks', 45, 'pending', strftime('%s','now')),
('best horse in rdr2', 45, 'pending', strftime('%s','now')),
('best inn salina ks', 45, 'pending', strftime('%s','now')),
('best medicine cast', 45, 'pending', strftime('%s','now')),
('best online casino', 45, 'pending', strftime('%s','now')),
('best zoo in kansas', 45, 'pending', strftime('%s','now')),
('best laptop brands', 45, 'pending', strftime('%s','now')),
('best phone carrier', 45, 'pending', strftime('%s','now')),
('best luggage scale', 45, 'pending', strftime('%s','now')),
('best printer brand', 45, 'pending', strftime('%s','now')),
('best vacuum sealer', 45, 'pending', strftime('%s','now')),
('best grill cleaner', 45, 'pending', strftime('%s','now')),
('best nas case 2026', 45, 'pending', strftime('%s','now')),
('best sata ssd 2026', 45, 'pending', strftime('%s','now')),
('best pc tower 2026', 45, 'pending', strftime('%s','now')),
('best led bulb 2026', 45, 'pending', strftime('%s','now')),
('best rucksack 2026', 45, 'pending', strftime('%s','now')),
('best joystick 2026', 45, 'pending', strftime('%s','now')),
('best bbq wichita ks', 45, 'pending', strftime('%s','now')),
('best instant coffee', 45, 'pending', strftime('%s','now')),
('best pizza derby ks', 45, 'pending', strftime('%s','now')),
('best protein powder', 45, 'pending', strftime('%s','now')),
('best quad exercises', 45, 'pending', strftime('%s','now')),
('best queen mattress', 45, 'pending', strftime('%s','now')),
('best cpu air cooler', 45, 'pending', strftime('%s','now')),
('best blender brands', 45, 'pending', strftime('%s','now')),
('best blender bottle', 45, 'pending', strftime('%s','now')),
('best luggage brands', 45, 'pending', strftime('%s','now')),
('best grilled cheese', 45, 'pending', strftime('%s','now')),
('best processor 2026', 45, 'pending', strftime('%s','now')),
('best water jug 2026', 45, 'pending', strftime('%s','now')),
('best cordless vacuum', 45, 'pending', strftime('%s','now')),
('best food wichita ks', 45, 'pending', strftime('%s','now')),
('best food in wichita', 45, 'pending', strftime('%s','now')),
('best jeans for women', 45, 'pending', strftime('%s','now')),
('best jason build dbd', 45, 'pending', strftime('%s','now')),
('best korean skincare', 45, 'pending', strftime('%s','now')),
('best knife sharpener', 45, 'pending', strftime('%s','now')),
('best lakes in kansas', 45, 'pending', strftime('%s','now')),
('best prime day deals', 45, 'pending', strftime('%s','now')),
('best qbs of all time', 45, 'pending', strftime('%s','now')),
('best vitamin c serum', 45, 'pending', strftime('%s','now')),
('best vibration plate', 45, 'pending', strftime('%s','now')),
('best western hays ks', 45, 'pending', strftime('%s','now')),
('best xbox controller', 45, 'pending', strftime('%s','now')),
('best zinc supplement', 45, 'pending', strftime('%s','now')),
('best mouse repellent', 45, 'pending', strftime('%s','now')),
('best microwave brand', 45, 'pending', strftime('%s','now')),
('best microwave ovens', 45, 'pending', strftime('%s','now')),
('best microwave meals', 45, 'pending', strftime('%s','now')),
('best dishwasher pods', 45, 'pending', strftime('%s','now')),
('best dishwasher soap', 45, 'pending', strftime('%s','now')),
('best mattresses 2026', 45, 'pending', strftime('%s','now')),
('best mattress brands', 45, 'pending', strftime('%s','now')),
('best backpack cooler', 45, 'pending', strftime('%s','now')),
('best grilled chicken', 45, 'pending', strftime('%s','now')),
('best nas drives 2026', 45, 'pending', strftime('%s','now')),
('best budget ssd 2026', 45, 'pending', strftime('%s','now')),
('best desk chair 2026', 45, 'pending', strftime('%s','now')),
('best work chair 2026', 45, 'pending', strftime('%s','now')),
('best table lamp 2026', 45, 'pending', strftime('%s','now')),
('best air filter 2026', 45, 'pending', strftime('%s','now')),
('best bed sheets 2026', 45, 'pending', strftime('%s','now')),
('best bt speaker 2026', 45, 'pending', strftime('%s','now')),
('best light bulb 2026', 45, 'pending', strftime('%s','now')),
('best blow dryer 2026', 45, 'pending', strftime('%s','now')),
('best men shaver 2026', 45, 'pending', strftime('%s','now')),
('best jet washer 2026', 45, 'pending', strftime('%s','now')),
('best nail drill 2026', 45, 'pending', strftime('%s','now')),
('best allergy medicine', 45, 'pending', strftime('%s','now')),
('best fiber supplement', 45, 'pending', strftime('%s','now')),
('best grass for kansas', 45, 'pending', strftime('%s','now')),
('best job search sites', 45, 'pending', strftime('%s','now')),
('best korean sunscreen', 45, 'pending', strftime('%s','now')),
('best lunch wichita ks', 45, 'pending', strftime('%s','now')),
('best obgyn wichita ks', 45, 'pending', strftime('%s','now')),
('best pizza wichita ks', 45, 'pending', strftime('%s','now')),
('best pizza in wichita', 45, 'pending', strftime('%s','now')),
('best queso in wichita', 45, 'pending', strftime('%s','now')),
('best sushi wichita ks', 45, 'pending', strftime('%s','now')),
('best steak wichita ks', 45, 'pending', strftime('%s','now')),
('best shows on netflix', 45, 'pending', strftime('%s','now')),
('best tacos wichita ks', 45, 'pending', strftime('%s','now')),
('best value auto sales', 45, 'pending', strftime('%s','now')),
('best way to boil eggs', 45, 'pending', strftime('%s','now')),
('best x files episodes', 45, 'pending', strftime('%s','now')),
('best y level for iron', 45, 'pending', strftime('%s','now')),
('best zero turn mowers', 45, 'pending', strftime('%s','now')),
('best sheets at target', 45, 'pending', strftime('%s','now')),
('best projector screen', 45, 'pending', strftime('%s','now')),
('best backpack sprayer', 45, 'pending', strftime('%s','now')),
('best backpacking tent', 45, 'pending', strftime('%s','now')),
('best desk lights 2026', 45, 'pending', strftime('%s','now'));
