// Vendored gazetteers (DATA). A generic list of REAL consumer/tech/software brands
// (helps candidate precision — and note that fabricated "trap" brands are, by
// definition, NOT real brands, so this legitimately favors real products) + a
// publisher/source stoplist + generic non-product Title-Case stopwords. Phase-0
// proof subset; expand from logged data later. No dependencies.
// Category clusters used for cross-category gating (so a query in one category
// won't surface a brand whose only home is an unrelated cluster). BRANDS below is
// derived from these: every brand is the flat union of all cluster arrays.
export const BRAND_CLUSTERS = {
  TECH: [
    'sony', 'samsung', 'apple', 'bose', 'sennheiser', 'soundcore', 'anker', 'jbl', 'beats', 'keychron',
    'nuphy', 'logitech', 'razer', 'corsair', 'ducky', 'leopold', 'hhkb', 'akko', 'dell', 'lg', 'asus', 'acer',
    'hp', 'lenovo', 'msi', 'gigabyte', 'benq', 'viewsonic', 'crucial', 'sandisk', 'western digital', 'wd',
    'seagate', 'kingston', 'teamgroup', 'nvidia', 'amd', 'intel', 'roborock', 'eufy', 'irobot', 'roomba',
    'shark', 'dyson', 'tineco', 'garmin', 'fitbit', 'whoop', 'polar', 'suunto', 'canon', 'nikon', 'fujifilm',
    'panasonic', 'gopro', 'dji', 'mailchimp', 'convertkit', 'kit', 'brevo', 'mailerlite', 'sendinblue',
    'hubspot', 'klaviyo', 'notion', 'airtable', 'slack', 'zoom', 'figma', 'canva', 'royal kludge', 'tp-link',
    'ugreen', 'synology', 'qnap', 'eight sleep', 'philips', 'nanit', 'vtech', 'motorola', 'peak design',
    'wandrd', 'incase', 'elgato', 'aukey', 'avermedia', 'obsbot', 'insta360', 'alienware', 'nzxt',
    'blackmagic', 'magewell', 'roku', 'amazon', 'google', 'tivo', 'google nest', 'ring', 'wyze', 'arlo',
    'blink', 'ecobee', 'ubiquiti', 'netgear', 'linksys', 'eero', 'd-link', 'arris', 'epson', 'optoma',
    'anker nebula', 'xgimi', 'vankyo', 'wemax', 'hisense', 'byintek', 'sonos', 'philips hue', 'lutron', 'lifx',
    'govee', 'nanoleaf', 'aqara', 'schlage', 'yale', 'august', 'honeywell', 'tplink kasa', 'shelly',
    'smartthings', 'abode', 'simplisafe', 'shure', 'rode', 'audio-technica', 'hyperx', 'streamlabs', 'atem',
    'cisco', 'starlink', 'mediabridge', 'trendnet', 'cudy', 'amcrest', 'reolink', 'lorex',
  ],
  APPAREL_FOOTWEAR: [
    'patagonia', 'lululemon', 'the north face', 'under armour', 'll bean', 'levi\'s', 'wrangler', 'old navy',
    'banana republic', 'j crew', 'madewell', 'everlane', 'uniqlo', 'zara', 'h&m', 'abercrombie', 'hollister',
    'american eagle', 'ralph lauren', 'polo ralph lauren', 'tommy hilfiger', 'calvin klein', 'lacoste',
    'brooks brothers', 'untuckit', 'vineyard vines', 'lands end', 'eddie bauer', 'columbia', 'carhartt',
    'dickies', 'rei co-op', 'athleta', 'vuori', 'alo yoga', 'free people', 'anthropologie', 'urban outfitters',
    'ann taylor', 'talbots', 'chico\'s', 'nordstrom', 'gucci', 'prada', 'burberry', 'armani', 'versace',
    'michael kors', 'kate spade', 'ted baker', 'aritzia', 'reformation', 'frank and oak', 'buck mason',
    'taylor stitch', 'outerknown', 'faherty', 'marine layer', 'todd snyder', 'ministry of supply',
    'mott & bow', 'fjallraven', 'arc\'teryx', 'asos', 'boohoo', 'fashion nova', 'spanx', 'skims',
    'true religion', 'g-star', 'diesel', 'ag jeans', 'citizens of humanity', 'rag & bone', '7 for all mankind',
    'hugo boss', 'club monaco', 'scotch & soda', 'ben sherman', 'fred perry', 'barbour', 'nike', 'adidas',
    'new balance', 'asics', 'brooks', 'hoka', 'saucony', 'puma', 'reebok', 'salomon', 'altra', 'mizuno',
    'converse', 'skechers', 'fila', 'crocs', 'timberland', 'dr martens', 'clarks', 'ecco', 'merrell', 'vasque',
    'danner', 'red wing', 'wolverine', 'thorogood', 'blundstone', 'birkenstock', 'teva', 'chaco', 'sorel',
    'sperry', 'cole haan', 'allen edmonds', 'johnston murphy', 'florsheim', 'rockport', 'bostonian',
    'thursday boot', 'allbirds', 'rothys', 'naturalizer', 'koio', 'oliver cabell', 'vivobarefoot',
    'xero shoes', 'topo athletic', 'veja', 'common projects', 'axel arigato', 'steve madden', 'aldo',
    'nine west', 'dansko', 'vivaia', 'hush puppies', 'lems', 'oboz', 'scarpa', 'la sportiva', 'lowa',
    'ferragamo', 'santoni', 'to boot new york', 'magnanni', 'stacy adams', 'kizik', 'tecovas', 'ariat',
    'justin boots', 'lucchese', 'frye', 'gymshark', 'outdoor voices', 'fabletics', 'on running', 'marmot',
    'mountain hardwear', 'outdoor research', 'kuhl', 'prana', 'icebreaker', 'smartwool', 'darn tough',
    'cotopaxi', 'mammut', 'helly hansen', 'canada goose', 'spyder', 'burton', 'tracksmith', 'ten thousand',
    'myprotein', 'sweaty betty', 'beyond yoga', 'girlfriend collective', 'carbon38', 'outdoor afro',
    'duluth trading', 'oakley', 'norrona', 'mountain equipment', 'decathlon', 'free people movement', 'p448',
    'first lite', 'sitka', 'kuiu', 'western rise', 'outlier', 'olukai', 'swiftwick', 'feetures', 'bombas',
    'quince', 'macy\'s', 'dior', 'chanel', 'givenchy', 'tom ford', 'maison margiela', 'dolce gabbana',
    'carolina herrera', 'pearl izumi', 'castelli', 'rapha', 'tory burch', 'louis vuitton', 'rains', 'filson',
  ],
  HOME_KITCHEN: [
    'steelcase', 'herman miller', 'hon', 'ikea', 'autonomous', 'uplift', 'flexispot', 'secretlab', 'lodge',
    'instant pot', 'ninja', 'cosori', 'breville', 'cuisinart', 'kitchenaid', 'vitamix', 'casper',
    'tempur-pedic', 'sealy', 'serta', 'stearns and foster', 'saatva', 'nectar', 'leesa', 'tuft and needle',
    'helix', 'avocado', 'dreamcloud', 'wink beds', 'winkbeds', 'brooklyn bedding', 'layla', 'ghostbed',
    'puffy', 'amerisleep', 'zinus', 'lucid', 'sleep number', 'simmons', 'beautyrest', 'tempur', 'cocoon',
    'casper sleep', 'big fig', 'nolah', 'plushbeds', 'naturepedic', 'molecule', 'eight sleep', 'ashley',
    'ashley furniture', 'la-z-boy', 'pottery barn', 'west elm', 'crate and barrel', 'wayfair',
    'room and board', 'ethan allen', 'restoration hardware', 'joybird', 'burrow', 'world market',
    'raymour and flanigan', 'havertys', 'bob\'s discount furniture', 'rooms to go', 'knoll', 'brooklinen',
    'parachute', 'boll and branch', 'buffy', 'casaluna', 'snowe', 'coyuchi', 'garnet hill', 'mellanni',
    'sferra', 'matouk', 'frette', 'pottery barn kids', 'the company store', 'ruggable', 'tempur-sealy',
    'my pillow', 'mypillow', 'pacific coast', 'downlite', 'coop home goods', 'purple mattress', 'yogabed',
    'dunlopillo', 'casper select', 'sven and son', 'allswell', 'cozy earth', 'quince', 'homegoods', 'macy\'s',
    'costco', 'novaform', 'kirkland signature', 'all-clad', 'le creuset', 'staub', 'calphalon', 't-fal',
    'tefal', 'anolon', 'scanpan', 'demeyere', 'great jones', 'caraway', 'our place', 'hexclad', 'greenpan',
    'tramontina', 'viking', 'mauviel', 'zwilling', 'henckels', 'wusthof', 'victorinox', 'miyabi',
    'messermeisser', 'messermeister', 'dalstrong', 'kramer', 'opinel', 'chicago cutlery', 'farberware',
    'rachael ray', 'gotham steel', 'blue diamond', 'ballarini', 'fissler', 'blendtec', 'nutribullet',
    'hamilton beach', 'black decker', 'oster', 'crock-pot', 'presto', 'dash', 'magic bullet', 'smeg',
    'delonghi', 'keurig', 'nespresso', 'jura', 'gaggia', 'rancilio', 'rocket espresso', 'la marzocco', 'lelit',
    'profitec', 'ascaso', 'fellow', 'baratza', 'bonavita', 'technivorm', 'moccamaster', 'chemex', 'bodum',
    'aeropress', 'wilfa', 'comandante', 'timemore', '1zpresso', 'stagg', 'philips', 'braun', 'krups',
    'mr coffee', 'bunn', 'behmor', 'bambino', 'anova', 'ninja foodi', 'tovala', 'balmuda', 'zojirushi',
    'instant brands', 'ramster', 'kohler', 'moen', 'delta', 'pfister', 'schlage', 'yale', 'august',
    'honeywell',
  ],
  BEAUTY: [
    'braun', 'cerave', 'cetaphil', 'neutrogena', 'olay', 'l\'oreal', 'maybelline', 'revlon', 'covergirl',
    'milk makeup', 'fenty beauty', 'rare beauty', 'glossier', 'the ordinary', 'paula\'s choice',
    'drunk elephant', 'tatcha', 'sunday riley', 'kiehl\'s', 'clinique', 'estee lauder', 'lancome', 'shiseido',
    'la roche-posay', 'vichy', 'eucerin', 'aveeno', 'first aid beauty', 'youth to the people',
    'summer fridays', 'supergoop', 'biossance', 'kiehls', 'bobbi brown', 'nars', 'urban decay', 'too faced',
    'benefit', 'tarte', 'charlotte tilbury', 'dior', 'chanel', 'armani beauty', 'givenchy', 'tom ford',
    'jo malone', 'le labo', 'byredo', 'maison margiela', 'diptyque', 'creed', 'dolce gabbana',
    'carolina herrera', 'olaplex', 'ouai', 'briogeo', 'moroccanoil', 'redken', 'pureology', 'kerastase',
    'living proof', 'garnier', 'pantene', 'head shoulders', 'tresemme', 'schwarzkopf', 'wella', 'nivea',
    'cremo', 'harry\'s', 'dollar shave club', 'gillette', 'old spice', 'every man jack', 'jack black', 'lume',
    'vaseline', 'burt\'s bees', 'carmex', 'aquaphor', 'vanicream', 'hada labo', 'cosrx', 'innisfree',
    'laneige', 'beauty of joseon', 'anastasia beverly hills', 'huda beauty', 'patrick ta', 'haus labs',
    'sally hansen',
  ],
  OUTDOOR: [
    'garmin', 'suunto', 'gopro', 'patagonia', 'the north face', 'll bean', 'eddie bauer', 'columbia',
    'rei co-op', 'fjallraven', 'arc\'teryx', 'barbour', 'salomon', 'altra', 'timberland', 'merrell', 'vasque',
    'danner', 'teva', 'chaco', 'sorel', 'xero shoes', 'topo athletic', 'lems', 'oboz', 'scarpa', 'la sportiva',
    'lowa', 'ariat', 'marmot', 'mountain hardwear', 'outdoor research', 'kuhl', 'prana', 'icebreaker',
    'smartwool', 'darn tough', 'cotopaxi', 'black diamond', 'mammut', 'helly hansen', 'canada goose', 'spyder',
    'burton', 'outdoor afro', 'oakley', 'patagonia provisions', 'norrona', 'mountain equipment', 'decathlon',
    'quechua', 'first lite', 'sitka', 'kuiu', 'swiftwick', 'victorinox', 'opinel', 'benchmade', 'osprey',
    'gregory', 'deuter', 'kelty', 'granite gear', 'mystery ranch', 'petzl', 'jetboil', 'big agnes', 'nemo',
    'therm-a-rest', 'sea to summit', 'coleman', 'exped', 'klymit', 'yeti', 'rtic', 'hydro flask', 'nalgene',
    'stanley', 'leatherman', 'gerber', 'biolite', 'goal zero', 'specialized', 'cannondale', 'santa cruz',
    'canyon', 'cervelo', 'bianchi', 'shimano', 'sram', 'yeti cycles', 'pearl izumi', 'castelli', 'rapha',
    'ortlieb', 'thule', 'shakespeare', 'shimano fishing', 'okuma', 'abu garcia', 'daiwa', 'st croix',
    'ugly stik', 'rapala', 'berkley', 'yakima', 'eagle creek', 'filson',
  ],
  TOOLS: [
    'benchmade', 'rachio', 'black decker', 'leatherman', 'gerber', 'dewalt', 'milwaukee', 'makita', 'bosch',
    'ryobi', 'ridgid', 'craftsman', 'kobalt', 'metabo', 'metabo hpt', 'hitachi', 'festool', 'porter-cable',
    'black and decker', 'skil', 'worx', 'hart', 'flex', 'hilti', 'skilsaw', 'genesis', 'chicago electric',
    'snap-on', 'klein tools', 'irwin', 'channellock', 'knipex', 'wera', 'wiha', 'estwing', 'vaughan',
    'crescent', 'gearwrench', 'husky', 'tekton', 'dremel', 'rotozip', 'fein', 'rockwell', 'greenworks',
    'stihl', 'husqvarna', 'echo', 'toro', 'cub cadet', 'john deere', 'scotts', 'fiskars', 'corona', 'felco',
    'ames', 'sun joe', 'snow joe', 'earthwise', 'troy-bilt', 'honda', 'generac', 'westinghouse', 'wagner',
    'graco', 'homeright', 'rust-oleum', 'behr', 'kilz', 'minwax', 'gorilla', 'loctite', 'titebond', 'shop-vac',
    'milwaukee packout', 'lenox', 'diablo', 'freud', 'kreg', 'rockler', 'woodpeckers', 'bessey', 'wolfcraft',
    'empire', 'swanson', 'johnson level', 'starrett', 'mitutoyo', 'little giant', 'werner', 'gorilla ladders',
    'louisville ladder', 'quikrete', 'owens corning', 'kohler', 'moen', 'delta', 'pfister', 'sharkbite',
    'oatey', 'milwaukee tool',
  ],
  PET: [
    'purina', 'blue buffalo', 'hill\'s science diet', 'royal canin', 'iams', 'pedigree', 'wellness', 'merrick',
    'taste of the wild', 'orijen', 'acana', 'nutro', 'rachael ray nutrish', 'diamond naturals', 'fromm',
    'canidae', 'nulo', 'instinct', 'ziwi peak', 'stella & chewy\'s', 'the farmer\'s dog', 'ollie', 'nom nom',
    'spot & tango', 'open farm', 'honest kitchen', 'freshpet', 'cesar', 'sheba', 'fancy feast', 'friskies',
    '9lives', 'meow mix', 'temptations', 'greenies', 'milk-bone', 'pup-peroni', 'kong', 'nylabone', 'chuckit',
    'outward hound', 'petsafe', 'frontline', 'advantage', 'seresto', 'kurgo', 'ruffwear', 'wild one', 'fable',
    'petlibro', 'litter robot', 'whisker', 'tidy cats', 'fresh step', 'arm & hammer',
    'world\'s best cat litter', 'dr elsey\'s', 'pretty litter', 'feliway', 'thundershirt', 'petmate',
    'midwest homes', 'frisco', 'blue-9', 'halo', 'pure balance', 'victor', 'earthborn holistic',
    'natural balance', 'solid gold', 'weruva', 'tiki cat', 'smalls', 'chewy', 'petco', 'petsmart', 'barkbox',
    'snuggle puppy', 'west paw', 'benebone', 'petkit',
  ],
  BABY: [
    'naturepedic', 'pottery barn kids', 'chicco', 'uppababy', 'nuna', 'britax', 'doona', 'bugaboo', 'babyzen',
    'maxi-cosi', 'evenflo', 'baby jogger', 'cybex', 'clek', 'diono', 'peg perego', 'stokke', 'bob gear',
    'mockingbird', 'joovy', 'ergobaby', 'babybjorn', 'lillebaby', 'wonderfold', 'veer', 'munchkin', 'skip hop',
    'infant optics', 'nanit', 'owlet', 'vtech', 'motorola', 'miku', 'hatch', 'fisher-price',
    'melissa and doug', 'little tikes', 'step2', 'hape', 'lovevery', 'lego', 'playmobil', 'magna-tiles',
    'green toys', 'manhattan toy', 'kidkraft', 'radio flyer', 'razor', 'playskool', 'leapfrog',
    'summer infant', 'ingenuity', '4moms', 'snuza', 'fridababy', 'boon', 'comotomo', 'dr browns',
    'philips avent', 'tommee tippee', 'medela', 'willow', 'elvie', 'nuby', 'dreft', 'baby brezza',
    'guava family', 'lalo', 'nuna baby', 'inglesina', 'silver cross', 'guava', 'delta children', 'graco baby',
    'safety 1st', 'regalo', 'owlet baby care', 'babylist', 'monica and andy', 'kyte baby', 'happiest baby',
    'snoo', 'newton baby', 'dock a tot', 'babymoov',
  ],
  BAGS_TRAVEL: [
    'michael kors', 'kate spade', 'fjallraven', 'cotopaxi', 'osprey', 'gregory', 'deuter', 'granite gear',
    'mystery ranch', 'ortlieb', 'thule', 'yakima', 'samsonite', 'away', 'tumi', 'rimowa', 'monos', 'july',
    'briggs & riley', 'travelpro', 'delsey', 'calpak', 'bric\'s', 'herschel', 'jansport', 'kanken',
    'peak design', 'wandrd', 'nomatic', 'bellroy', 'tom bihn', 'timbuk2', 'chrome industries', 'incase',
    'tory burch', 'fossil', 'montblanc', 'secrid', 'ekster', 'saddleback leather', 'louis vuitton',
    'longchamp', 'dagne dover', 'baggu', 'lo & sons', 'rains', 'knomo', 'ebags', 'eagle creek', 'high sierra',
    'swissgear', 'wenger', 'timex', 'casio', 'seiko', 'citizen', 'rolex', 'tag heuer', 'tissot', 'shinola',
    'mvmt', 'daniel wellington', 'skagen', 'bulova', 'orient', 'g-shock', 'filson', 'rolling thunder',
    'manhattan portage', 'stubble & co', 'db journey', 'antler', 'american tourister', 'kipling',
    'vera bradley',
  ],
};
export const BRANDS = new Set(Object.values(BRAND_CLUSTERS).flat());

// Source/publisher names — never a product candidate.
export const PUBLISHERS = new Set([
  'rtings', 'wirecutter', 'tom', "tom's hardware", 'toms hardware', 'ars technica', 'the verge',
  'engadget', 'cnet', 'pcmag', 'pc gamer', 'soundguys', 'storagereview', 'gamers nexus',
  'hardware unboxed', 'reddit', 'hacker news', 'hackernews', 'youtube', 'amazon', 'google',
  'best buy', 'walmart', 'target', 'newegg', 'tripadvisor', 'yelp', 'emailtooltester',
  'ergonomicstrends', 'dealsblog', 'techdeals', 'saasdeals', 'topbestlists', 'topchairs',
  'official store', 'official',
]);

// Generic Title-Case words that start/are noise, not products.
export const STOPWORDS = new Set([
  'the', 'best', 'top', 'a', 'an', 'of', 'for', 'and', 'or', 'in', 'on', 'with', 'under', 'vs',
  'our', 'we', 'i', 'buy', 'review', 'reviews', 'guide', 'guides', 'tested', 'testing', 'lab',
  'budget', 'value', 'pick', 'picks', 'sponsored', 'affiliate',
  'official', 'store', 'new', 'use', 'every', 'this', 'that', 'it', 'they', 'their',
]);
// NOTE: 'pro'/'max'/'ultra'/'elite'/'plus' are deliberately NOT stopwords — they are
// legitimate model-name suffixes (Shark AI Ultra, eufy X8 Pro). The brand-or-code
// keep-rule filters fluff instead.
